// generated from https://www.virginmedia.com/content/dam/virginmedia/dotcom/documents/Redwood/ChannelGuide_June2019.pdf
// linked from https://www.virginmedia.com/virgin-tv-edit/tips-and-tricks/virgin-tv-channel-guide
const channels = [
    {"number": "100", "name": "Virgin Media Previews"},
    {"number": "101", "name": "BBC One"},
    {"number": "102", "name": "BBC Two HD"},
    {"number": "103", "name": "ITV HD"},
    {"number": "104", "name": "Channel 4"},
    {"number": "105", "name": "Channel 5"},
    {"number": "106", "name": "E4"},
    {"number": "107", "name": "BBC Four HD"},
    {"number": "108", "name": "BBC One HD"},
    {"number": "109", "name": "Sky One HD"},
    {"number": "110", "name": "Sky One"},
    {"number": "111", "name": "Sky Witness HD"},
    {"number": "112", "name": "Sky Witness"},
    {"number": "113", "name": "ITV HD"},
    {"number": "114", "name": "ITV +1"},
    {"number": "115", "name": "ITV2"},
    {"number": "116", "name": "ITV2 +1"},
    {"number": "117", "name": "ITV3"},
    {"number": "118", "name": "ITV4"},
    {"number": "119", "name": "ITVBe"},
    {"number": "120", "name": "ITVBe +1"},
    {"number": "121", "name": "Sky Two"},
    {"number": "122", "name": "Sky Arts"},
    {"number": "123", "name": "Pick"},
    {"number": "124", "name": "GOLD HD"},
    {"number": "125", "name": "W"},
    {"number": "126", "name": "alibi"},
    {"number": "127", "name": "Dave"},
    {"number": "128", "name": "Really"},
    {"number": "129", "name": "Yesterday"},
    {"number": "130", "name": "Drama"},
    {"number": "131", "name": "Dave ja vu"},
    {"number": "132", "name": "Comedy Central"},
    {"number": "133", "name": "Comedy Central +1"},
    {"number": "134", "name": "MTV"},
    {"number": "135", "name": "SYFY"},
    {"number": "136", "name": "SYFY +1"},
    {"number": "137", "name": "Universal TV"},
    {"number": "138", "name": "Universal TV +1"},
    {"number": "139", "name": "Challenge"},
    {"number": "140", "name": "Sky Witness +1"},
    {"number": "141", "name": "Channel 4 HD"},
    {"number": "142", "name": "Channel 4 +1"},
    {"number": "143", "name": "4Seven"},
    {"number": "145", "name": "E4 HD"},
    {"number": "146", "name": "E4 +1"},
    {"number": "147", "name": "More4"},
    {"number": "148", "name": "CBS Reality"},
    {"number": "149", "name": "Horror Channel"},
    {"number": "150", "name": "Channel 5 HD"},
    {"number": "151", "name": "5STAR"},
    {"number": "152", "name": "5Select"},
    {"number": "153", "name": "5 USA"},
    {"number": "154", "name": "5Spike"},
    {"number": "155", "name": "Channel 5 +1"},
    {"number": "156", "name": "E!"},
    {"number": "157", "name": "FOX"},
    {"number": "158", "name": "FOX +1"},
    {"number": "159", "name": "Regional Channels"},
    {"number": "160", "name": "Real Lives"},
    {"number": "161", "name": "BBC Alba"},
    {"number": "162", "name": "BBC Scotland HD*"},
    {"number": "164", "name": "Universal TV HD"},
    {"number": "165", "name": "SYFY HD"},
    {"number": "166", "name": "S4C HD"},
    {"number": "167", "name": "TLC"},
    {"number": "168", "name": "TLC HD"},
    {"number": "169", "name": "TLC +1"},
    {"number": "170", "name": "Investigation Discovery"},
    {"number": "171", "name": "Investigation Discovery +1"},
    {"number": "172", "name": "Quest"},
    {"number": "173", "name": "Quest +1"},
    {"number": "174", "name": "ITV3 +1"},
    {"number": "175", "name": "ITV4 +1"},
    {"number": "176", "name": "ITV2 HD"},
    {"number": "177", "name": "ITV3 HD"},
    {"number": "178", "name": "ITV4 HD"},
    {"number": "179", "name": "ITVBe HD"},
    {"number": "180", "name": "Challenge +1"},
    {"number": "181", "name": "Comedy Central HD"},
    {"number": "182", "name": "Comedy Central Extra"},
    {"number": "183", "name": "MTV HD"},
    {"number": "184", "name": "BET"},
    {"number": "185", "name": "5 USA +1"},
    {"number": "186", "name": "5STAR +1"},
    {"number": "187", "name": "Paramount Network HD"},
    {"number": "188", "name": "Paramount Network"},
    {"number": "189", "name": "True Entertainment"},
    {"number": "190", "name": "W +1"},
    {"number": "191", "name": "alibi +1"},
    {"number": "192", "name": "CBS Justice"},
    {"number": "193", "name": "Sony Crime Channel"},
    {"number": "194", "name": "GOLD +1"},
    {"number": "195", "name": "More4 HD"},
    {"number": "196", "name": "More4 +1"},
    {"number": "197", "name": "CBS Drama"},
    {"number": "198", "name": "YouTube"},
    {"number": "199", "name": "FOX HD"},
    {"number": "200", "name": "Yesterday +1"},
    {"number": "201", "name": "CBS Reality +1"},
    {"number": "202", "name": "Horror Channel +1"},
    {"number": "203", "name": "4Seven HD"},
    {"number": "204", "name": "Netflix"},
    {"number": "206", "name": "Sky Arts HD"},
    {"number": "207", "name": "Real Lives +1"},
    {"number": "208", "name": "Lifetime® HD"},
    {"number": "209", "name": "Crime + Investigation HD"},
    {"number": "210", "name": "hayu"},
    {"number": "211", "name": "W HD"},
    {"number": "212", "name": "True Crime"},
    {"number": "213", "name": "DMAX"},
    {"number": "214", "name": "DMAX +1"},
    {"number": "215", "name": "Quest Red"},
    {"number": "216", "name": "BLAZE®"},
    {"number": "217", "name": "Quest HD"},
    {"number": "218", "name": "YourTV"},
    {"number": "219", "name": "VICE"},
    {"number": "220", "name": "True Entertainment +1"},
    {"number": "222", "name": "Crime + Investigation +1"},
    {"number": "225", "name": "Lifetime® +1"},
    {"number": "226", "name": "alibi HD"},
    {"number": "227", "name": "Dave HD"},
    {"number": "991", "name": "BBC RB 1"},
    {"number": "999", "name": "Virgin TV Ultra HD"},
    {"number": "245", "name": "Eden"},
    {"number": "246", "name": "Eden +1"},
    {"number": "247", "name": "Eden HD"},
    {"number": "250", "name": "Discovery"},
    {"number": "251", "name": "Discovery HD"},
    {"number": "252", "name": "Discovery +1"},
    {"number": "256", "name": "Animal Planet"},
    {"number": "257", "name": "Animal Planet HD"},
    {"number": "258", "name": "Animal Planet +1"},
    {"number": "259", "name": "Discovery Science"},
    {"number": "260", "name": "Discovery Science +1"},
    {"number": "261", "name": "Discovery Turbo"},
    {"number": "262", "name": "Discovery History"},
    {"number": "263", "name": "Discovery History +1"},
    {"number": "264", "name": "National Geographic WILD"},
    {"number": "265", "name": "National Geographic WILD HD"},
    {"number": "266", "name": "National Geographic"},
    {"number": "267", "name": "National Geographic +1"},
    {"number": "268", "name": "National Geographic HD"},
    {"number": "269", "name": "Together"},
    {"number": "270", "name": "HISTORY® HD"},
    {"number": "271", "name": "HISTORY® +1"},
    {"number": "273", "name": "HISTORY2® HD"},
    {"number": "276", "name": "PBS America"},
    {"number": "277", "name": "Forces TV"},
    {"number": "278", "name": "Good Food"},
    {"number": "279", "name": "Good Food HD"},
    {"number": "280", "name": "Good Food +1"},
    {"number": "281", "name": "Home"},
    {"number": "282", "name": "Home +1"},
    {"number": "284", "name": "Discovery Home & Health"},
    {"number": "285", "name": "Discovery Home & Health +1"},
    {"number": "286", "name": "Discovery Shed"},
    {"number": "287", "name": "God Channel"},
    {"number": "291", "name": "Food Network"},
    {"number": "292", "name": "Travel Channel"},
    {"number": "293", "name": "Love Nature HD"},
    {"number": "294", "name": "Love Nature"},
    {"number": "295", "name": "Smithsonian Channel HD"},
    {"number": "298", "name": "Horse & Country"},
    {"number": "300", "name": "VM Music"},
    {"number": "310", "name": "MTV Music"},
    {"number": "311", "name": "MTV Live HD"},
    {"number": "312", "name": "MTV Hits"},
    {"number": "313", "name": "MTV Base"},
    {"number": "314", "name": "Club MTV"},
    {"number": "315", "name": "MTV Rocks"},
    {"number": "316", "name": "VH1"},
    {"number": "318", "name": "MTV OMG"},
    {"number": "330", "name": "Box Upfront"},
    {"number": "335", "name": "The Box"},
    {"number": "336", "name": "Box Hits"},
    {"number": "337", "name": "4Music"},
    {"number": "338", "name": "Kiss"},
    {"number": "340", "name": "Magic"},
    {"number": "342", "name": "Kerrang!"},
    {"number": "344", "name": "Vevo"},
    {"number": "345", "name": "Clubland TV"},
    {"number": "346", "name": "Now 80s"},
    {"number": "347", "name": "Now 90s"},
    {"number": "348", "name": "Total Country"},
    {"number": "400", "name": "Virgin Movies Previews"},
    {"number": "401", "name": "Sky Cinema Premiere HD"},
    {"number": "402", "name": "Sky Cinema Premiere +1"},
    {"number": "403", "name": "Sky Cinema Hits HD"},
    {"number": "404", "name": "Sky Cinema Greats HD"},
    {"number": "405", "name": "Sky Cinema Disney HD"},
    {"number": "406", "name": "Sky Cinema Family HD"},
    {"number": "407", "name": "Sky Cinema Action HD"},
    {"number": "408", "name": "Sky Cinema Comedy HD"},
    {"number": "409", "name": "Sky Cinema Thriller HD"},
    {"number": "410", "name": "Sky Cinema Drama HD"},
    {"number": "411", "name": "Sky Cinema Sci-Fi & Horror HD"},
    {"number": "412", "name": "Sky Cinema Select HD"},
    {"number": "415", "name": "TCM"},
    {"number": "416", "name": "TCM HD"},
    {"number": "417", "name": "TCM +1"},
    {"number": "419", "name": "Movies 24"},
    {"number": "420", "name": "Movies 24 +"},
    {"number": "424", "name": "True Movies"},
    {"number": "425", "name": "Sony Movie Channel"},
    {"number": "426", "name": "Movies4Men"},
    {"number": "428", "name": "Film4"},
    {"number": "429", "name": "Film4 HD"},
    {"number": "430", "name": "Film4 +1"},
    {"number": "431", "name": "Sky Cinema Premiere"},
    {"number": "433", "name": "Sky Cinema Hits"},
    {"number": "434", "name": "Sky Cinema Greats"},
    {"number": "435", "name": "Sky Cinema Disney"},
    {"number": "436", "name": "Sky Cinema Family"},
    {"number": "437", "name": "Sky Cinema Action"},
    {"number": "438", "name": "Sky Cinema Comedy"},
    {"number": "439", "name": "Sky Cinema Thriller"},
    {"number": "440", "name": "Sky Cinema Drama"},
    {"number": "441", "name": "Sky Cinema Sci-Fi & Horror"},
    {"number": "442", "name": "Sky Cinema Select"},
    {"number": "445", "name": "Talking Pictures TV"},
    {"number": "501", "name": "Sky Sports Main Event HD"},
    {"number": "502", "name": "Sky Sports Premier League HD"},
    {"number": "503", "name": "Sky Sports Football HD"},
    {"number": "504", "name": "Sky Sports Cricket HD"},
    {"number": "505", "name": "Sky Sports Golf HD"},
    {"number": "506", "name": "Sky Sports F1® HD"},
    {"number": "507", "name": "Sky Sports Action HD"},
    {"number": "508", "name": "Sky Sports Arena HD"},
    {"number": "509", "name": "Sky Sports News HD"},
    {"number": "510", "name": "Sky Sports Mix HD"},
    {"number": "511", "name": "Sky Sports Main Event"},
    {"number": "512", "name": "Sky Sports Premier League"},
    {"number": "513", "name": "Sky Sports Football"},
    {"number": "514", "name": "Sky Sports Cricket"},
    {"number": "515", "name": "Sky Sports Golf"},
    {"number": "516", "name": "Sky Sports F1®"},
    {"number": "517", "name": "Sky Sports Action"},
    {"number": "518", "name": "Sky Sports Arena"},
    {"number": "519", "name": "Sky Sports News"},
    {"number": "520", "name": "Sky Sports Mix"},
    {"number": "521", "name": "Eurosport 1 HD"},
    {"number": "522", "name": "Eurosport 2 HD"},
    {"number": "523", "name": "Eurosport 1"},
    {"number": "524", "name": "Eurosport 2"},
    {"number": "526", "name": "MUTV"},
    {"number": "527", "name": "BT Sport 1 HD"},
    {"number": "528", "name": "BT Sport 2 HD"},
    {"number": "529", "name": "BT Sport 3 HD"},
    {"number": "530", "name": "BT Sport ESPN HD"},
    {"number": "531", "name": "BT Sport 4K UHD"},
    {"number": "535", "name": "Sky Sports Racing"},
    {"number": "536", "name": "Racing TV HD"},
    {"number": "544", "name": "LFC TV HD"},
    {"number": "546", "name": "BoxNation"},
    {"number": "551", "name": "Premier Sports 1 HD"},
    {"number": "552", "name": "Premier Sports 2 HD"},
    {"number": "553", "name": "FreeSports HD"},
    {"number": "601", "name": "BBC News HD"},
    {"number": "602", "name": "Sky News"},
    {"number": "603", "name": "Sky News HD"},
    {"number": "605", "name": "BBC Parliament"},
    {"number": "607", "name": "CNN"},
    {"number": "609", "name": "Bloomberg HD"},
    {"number": "613", "name": "CNBC"},
    {"number": "620", "name": "Euronews"},
    {"number": "621", "name": "NDTV 24x7"},
    {"number": "622", "name": "Al Jazeera English"},
    {"number": "624", "name": "France 24 English HD"},
    {"number": "625", "name": "NHKworld HD"},
    {"number": "700", "name": "My Virgin TV Kids"},
    {"number": "701", "name": "CBBC HD"},
    {"number": "702", "name": "CBeebies HD"},
    {"number": "703", "name": "Baby TV"},
    {"number": "704", "name": "Cartoon Network"},
    {"number": "705", "name": "Cartoon Network +1"},
    {"number": "706", "name": "Cartoonito"},
    {"number": "707", "name": "Disney XD"},
    {"number": "712", "name": "Nickelodeon"},
    {"number": "713", "name": "Nick +1"},
    {"number": "714", "name": "Nick HD"},
    {"number": "715", "name": "Nick Jr."},
    {"number": "716", "name": "Nick Jr. Too"},
    {"number": "717", "name": "Nicktoons"},
    {"number": "724", "name": "Disney Channel"},
    {"number": "725", "name": "Disney Channel +1"},
    {"number": "727", "name": "Disney Junior"},
    {"number": "730", "name": "Boomerang"},
    {"number": "731", "name": "Boomerang +1"},
    {"number": "732", "name": "Cartoon Network HD"},
    {"number": "734", "name": "CITV"},
    {"number": "736", "name": "Pop"},
    {"number": "737", "name": "Tiny Pop"},
    {"number": "739", "name": "ZooMoo HD"},
    {"number": "740", "name": "QVC"},
    {"number": "741", "name": "QVC Beauty"},
    {"number": "742", "name": "QVC Style"},
    {"number": "747", "name": "Ideal World"},
    {"number": "748", "name": "Create and Craft"},
    {"number": "755", "name": "Gems TV"},
    {"number": "756", "name": "Jewellery Maker"},
    {"number": "757", "name": "TJC"},
    {"number": "800", "name": "Desi App Pack"},
    {"number": "801", "name": "Star Gold HD"},
    {"number": "802", "name": "Star Bharat"},
    {"number": "803", "name": "Star Plus HD"},
    {"number": "805", "name": "SONY TV Asia HD"},
    {"number": "806", "name": "SONY Max HD"},
    {"number": "807", "name": "SONY SAB"},
    {"number": "809", "name": "Zee TV"},
    {"number": "810", "name": "Zee Cinema HD"},
    {"number": "815", "name": "B4U Movies"},
    {"number": "816", "name": "B4U Music"},
    {"number": "826", "name": "Colors TV"},
    {"number": "827", "name": "Colors Rishtey"},
    {"number": "828", "name": "Colors Cineplex"},
    {"number": "829", "name": "NDTV Good Times"},
    {"number": "831", "name": "Al Jazeera Arabic"},
    {"number": "832", "name": "France 24 French HD"},
    {"number": "833", "name": "HUM Europe"},
    {"number": "836", "name": "NDTV India"},
    {"number": "837", "name": "NDTV Spice"},
    {"number": "838", "name": "Islam Channel"},
    {"number": "839", "name": "Islam Channel Urdu"},
    {"number": "840", "name": "BritAsia TV"},
    {"number": "841", "name": "MTV Beats"},
    {"number": "851", "name": "BBC One AD"},
    {"number": "852", "name": "BBC Two AD"},
    {"number": "853", "name": "ITV AD"},
    {"number": "854", "name": "Channel 4 AD"},
    {"number": "855", "name": "Channel 5 AD"},
    {"number": "856", "name": "S4C AD"},
    {"number": "159", "name": "Regional Channels"},
    {"number": "861", "name": "BBC One England"},
    {"number": "862", "name": "BBC One Scotland"},
    {"number": "863", "name": "BBC One NI"},
    {"number": "864", "name": "BBC One Wales"},
    {"number": "865", "name": "BBC Two England"},
    {"number": "901", "name": "BBC Radio 1"},
    {"number": "902", "name": "BBC Radio 2"},
    {"number": "903", "name": "BBC Radio 3"},
    {"number": "904", "name": "BBC Radio 4"},
    {"number": "905", "name": "BBC Radio 5 Live"},
    {"number": "906", "name": "BBC World Service"},
    {"number": "907", "name": "BBC Radio 1 Xtra"},
    {"number": "908", "name": "BBC Radio 5 Live Sports Extra"},
    {"number": "909", "name": "BBC Radio 6 Music"},
    {"number": "910", "name": "BBC Radio 4 Extra"},
    {"number": "911", "name": "BBC Radio 4 LW"},
    {"number": "912", "name": "BBC Asian Network"},
    {"number": "913", "name": "BBC Radio Cymru 2"},
    {"number": "915", "name": "Absolute Radio"},
    {"number": "916", "name": "Smooth Radio"},
    {"number": "917", "name": "RTE Radio"},
    {"number": "918", "name": "Heart FM"},
    {"number": "919", "name": "LBC"},
    {"number": "920", "name": "World Radio Network"},
    {"number": "921", "name": "Heart 80s"},
    {"number": "922", "name": "Classic FM"},
    {"number": "923", "name": "Gold"},
    {"number": "924", "name": "Planet Rock"},
    {"number": "927", "name": "talkSPORT"},
    {"number": "928", "name": "Magic"},
    {"number": "930", "name": "BBC Radio Scotland"},
    {"number": "931", "name": "BBC Radio Wales"},
    {"number": "932", "name": "BBC Radio Ulster"},
    {"number": "933", "name": "BBC Radio Foyle"},
    {"number": "934", "name": "BBC Radio NanGaidheal"},
    {"number": "936", "name": "BBC Radio Cymru"},
    {"number": "937", "name": "BBC London"},
    {"number": "951", "name": "Absolute 80s"},
    {"number": "952", "name": "Absolute Classic Rock"},
    {"number": "958", "name": "Capital"},
    {"number": "959", "name": "Capital XTRA"},
    {"number": "960", "name": "Radio X"},
    {"number": "963", "name": "Kiss FM"},
    {"number": "997", "name": "Virgin TV Welcome"},
    {"number": "998", "name": "VM Previews"}
];
export default channels;