// generated from https://www.virginmedia.com/content/dam/virginmedia/dotcom/documents/Redwood/ChannelGuide_June2019.pdf
// linked from https://www.virginmedia.com/virgin-tv-edit/tips-and-tricks/virgin-tv-channel-guide
const channels = [
    {"number": "100", "name": "Virgin TV Showcase"},
    {"number": "101", "name": "BBC One HD"},
    {"number": "102", "name": "BBC Two HD"},
    {"number": "103", "name": "ITV1 HD & STV HD"},
    {"number": "104", "name": "Channel 4/HD & S4C HD"},
    {"number": "105", "name": "Channel 5 HD"},
    {"number": "106", "name": "E4 HD"},
    {"number": "107", "name": "BBC Three HD & BBC Four HD"},
    {"number": "108", "name": "BBC Four HD/Channel 4 HD Wales"},
    {"number": "109", "name": "Sky Showcase HD"},
    {"number": "110", "name": "Sky Witness HD"},
    {"number": "111", "name": "Sky Max HD"},
    {"number": "112", "name": "Sky Comedy HD"},
    {"number": "113", "name": "BBC Three HD Scotland & Wales"},
    {"number": "114", "name": "alibi HD"},
    {"number": "115", "name": "ITV2 HD"},
    {"number": "116", "name": "Drama HD"},
    {"number": "117", "name": "ITV3 HD"},
    {"number": "118", "name": "ITV4 HD"},
    {"number": "119", "name": "ITVBe HD"},
    {"number": "120", "name": "5 USA"},
    {"number": "121", "name": "Sky Crime HD"},
    {"number": "122", "name": "Sky Sci-Fi HD"},
    {"number": "123", "name": "Sky Arts HD"},
    {"number": "124", "name": "GOLD HD"},
    {"number": "125", "name": "W HD"},
    {"number": "126", "name": "5STAR"},
    {"number": "127", "name": "Dave HD"},
    {"number": "128", "name": "Really"},
    {"number": "129", "name": "Yesterday HD"},
    {"number": "130", "name": "5ACTION HD"},
    {"number": "131", "name": "Sky HISTORYHD"},
    {"number": "132", "name": "Comedy Central HD"},
    {"number": "133", "name": "Crime + Investigation HD"},
    {"number": "134", "name": "MTV HD"},
    {"number": "135", "name": "Sky Mix"},
    {"number": "136", "name": "Together"},
    {"number": "137", "name": "Quest HD"},
    {"number": "138", "name": "5Select"},
    {"number": "139", "name": "Challenge"},
    {"number": "140", "name": "Sky Arts"},
    {"number": "143", "name": "4Seven HD"},
    {"number": "144", "name": "E4 Extra"},
    {"number": "147", "name": "More4 HD"},
    {"number": "148", "name": "CBS Reality"},
    {"number": "149", "name": "Legend"},
    {"number": "150", "name": "That’s TV"},
    {"number": "154", "name": "Comedy Central Extra"},
    {"number": "156", "name": "Sky Replay"},
    {"number": "159", "name": "Regional Channels"},
    {"number": "160", "name": "E! HD"},
    {"number": "161", "name": "BBC Alba"},
    {"number": "162", "name": "5USA"},
    {"number": "164", "name": "S4C HD"},
    {"number": "165", "name": "TLC HD"},
    {"number": "166", "name": "Investigation Discovery"},
    {"number": "168", "name": "Quest Red"},
    {"number": "169", "name": "DMAX"},
    {"number": "170", "name": "GREAT TV"},
    {"number": "171", "name": "Horror Xtra"},
    {"number": "172", "name": "RealityXtra"},
    {"number": "174", "name": "BLAZE"},
    {"number": "175", "name": "Virgin TV Ultra HD"},
    {"number": "176", "name": "Eden HD"},
    {"number": "177", "name": "Discovery HD"},
    {"number": "178", "name": "Animal Planet HD"},
    {"number": "179", "name": "Discovery Science"},
    {"number": "180", "name": "Discovery Turbo"},
    {"number": "181", "name": "Discovery History"},
    {"number": "182", "name": "National Geographic WILD HD"},
    {"number": "183", "name": "National Geographic HD"},
    {"number": "186", "name": "Sky HISTORY2HD"},
    {"number": "187", "name": "PBS America"},
    {"number": "188", "name": "Sky Documentaries HD"},
    {"number": "189", "name": "Sky Nature HD"},
    {"number": "190", "name": "Food Network"},
    {"number": "191", "name": "HGTV"},
    {"number": "192", "name": "God TV"},
    {"number": "360", "name": "Welcome"},
    {"number": "204", "name": "Netflix"},
    {"number": "205", "name": "Prime Video"},
    {"number": "220", "name": "Inside Crime"},
    {"number": "221", "name": "Real Wild"},
    {"number": "222", "name": "Mystery TV"},
    {"number": "223", "name": "Haunt TV"},
    {"number": "224", "name": "History Hit"},
    {"number": "230", "name": "Homes Under The Hammer"},
    {"number": "231", "name": "Great British Menu"},
    {"number": "232", "name": "Tastemade"},
    {"number": "242", "name": "NextUp Live Comedy"},
    {"number": "243", "name": "The Chat Show Channel"},
    {"number": "244", "name": "Baywatch"},
    {"number": "250", "name": "Deal Or No Deal"},
    {"number": "251", "name": "Fear Factor"},
    {"number": "252", "name": "Wipeout Xtra"},
    {"number": "991", "name": "BBC Red Button HD"},
    {"number": "998", "name": "Virgin TV Highlights"},
    {"number": "999", "name": "Virgin TV Ultra HD"},
    {"number": "280", "name": "MTV Music"},
    {"number": "281", "name": "MTV Live HD"},
    {"number": "282", "name": "MTV Hits"},
    {"number": "283", "name": "MTV 90s"},
    {"number": "284", "name": "MTV 80s"},
    {"number": "285", "name": "The Box"},
    {"number": "286", "name": "4Music"},
    {"number": "288", "name": "Kiss"},
    {"number": "289", "name": "Magic"},
    {"number": "290", "name": "Kerrang!"},
    {"number": "291", "name": "Vevo"},
    {"number": "292", "name": "Clubland TV"},
    {"number": "293", "name": "Now 70s"},
    {"number": "294", "name": "Now 80s"},
    {"number": "295", "name": "Now Rock"},
    {"number": "296", "name": "That’s 60s"},
    {"number": "303", "name": "ITV1 +1 & STV +1"},
    {"number": "304", "name": "Channel 4 +1"},
    {"number": "305", "name": "Channel 5 +1"},
    {"number": "306", "name": "E4 +1"},
    {"number": "310", "name": "Sky Witness +1"},
    {"number": "314", "name": "alibi +1"},
    {"number": "315", "name": "ITV2 +1"},
    {"number": "316", "name": "Drama HD +1"},
    {"number": "317", "name": "ITV3 +1"},
    {"number": "318", "name": "ITV4 +1"},
    {"number": "319", "name": "ITVBe +1"},
    {"number": "320", "name": "5 USA +1"},
    {"number": "321", "name": "Sky Crime +1"},
    {"number": "324", "name": "GOLD +1"},
    {"number": "325", "name": "W +1"},
    {"number": "326", "name": "5STAR +1"},
    {"number": "327", "name": "Dave ja vu"},
    {"number": "329", "name": "Yesterday HD +1"},
    {"number": "331", "name": "Sky HISTORY +1"},
    {"number": "332", "name": "Comedy Central +1"},
    {"number": "333", "name": "Crime + Investigation +1"},
    {"number": "337", "name": "Quest +1"},
    {"number": "347", "name": "More4 +1"},
    {"number": "348", "name": "CBS Reality +1"},
    {"number": "365", "name": "TLC +1"},
    {"number": "366", "name": "Investigation Discovery +1"},
    {"number": "369", "name": "DMAX +1"},
    {"number": "371", "name": "HorrorXtra +1"},
    {"number": "376", "name": "Eden +1"},
    {"number": "377", "name": "Discovery +1"},
    {"number": "378", "name": "Animal Planet +1"},
    {"number": "379", "name": "Discovery Science +1"},
    {"number": "381", "name": "Discovery History +1"},
    {"number": "383", "name": "National Geographic +1"},
    {"number": "391", "name": "HGTV +1"},
    {"number": "400", "name": "Virgin Movies & Store"},
    {"number": "401", "name": "Sky Cinema Premiere HD"},
    {"number": "402", "name": "Sky Cinema Select HD"},
    {"number": "403", "name": "Sky Cinema Hits HD"},
    {"number": "404", "name": "Sky Cinema Greats HD"},
    {"number": "406", "name": "Sky Cinema Family HD"},
    {"number": "407", "name": "Sky Cinema Action HD"},
    {"number": "408", "name": "Sky Cinema Comedy HD"},
    {"number": "409", "name": "Sky Cinema Thriller HD"},
    {"number": "410", "name": "Sky Cinema Drama HD"},
    {"number": "411", "name": "Sky Cinema Sci-Fi & Horror HD"},
    {"number": "412", "name": "Sky Cinema Animation HD"},
    {"number": "419", "name": "Movies 24"},
    {"number": "420", "name": "Movies 24 +1"},
    {"number": "424", "name": "Great! Romance"},
    {"number": "425", "name": "Great! Movies"},
    {"number": "426", "name": "Great! Action"},
    {"number": "428", "name": "Film4 HD"},
    {"number": "430", "name": "Film4 +1"},
    {"number": "445", "name": "Talking Pictures TV"},
    {"number": "501", "name": "Sky Sports Main Event/HD"},
    {"number": "502", "name": "Sky Sports Premier League/HD"},
    {"number": "503", "name": "Sky Sports Football/HD"},
    {"number": "504", "name": "Sky Sports Cricket/HD"},
    {"number": "505", "name": "Sky Sports Golf/HD"},
    {"number": "506", "name": "Sky Sports F1®/HD"},
    {"number": "507", "name": "Sky Sports Action/HD"},
    {"number": "508", "name": "Sky Sports Arena/HD"},
    {"number": "509", "name": "Sky Sports News HD"},
    {"number": "510", "name": "Sky Sports Mix HD"},
    {"number": "519", "name": "Sky Sports Racing HD"},
    {"number": "521", "name": "Eurosport 1 HD"},
    {"number": "522", "name": "Eurosport 2 HD"},
    {"number": "526", "name": "MUTV"},
    {"number": "527", "name": "TNT Sports 1 HD"},
    {"number": "528", "name": "TNT Sports 2 HD"},
    {"number": "529", "name": "TNT Sports 3 HD"},
    {"number": "530", "name": "TNT Sports 4 HD"},
    {"number": "531", "name": "TNT Sports Ultimate"},
    {"number": "532", "name": "Sky Sports Main Event UHD"},
    {"number": "533", "name": "Sky Sports F1® UHD"},
    {"number": "534", "name": "Sky Sports UHD"},
    {"number": "535", "name": "Sky Sports UHD 2"},
    {"number": "536", "name": "Racing TV HD"},
    {"number": "544", "name": "LFC TV HD"},
    {"number": "551", "name": "Viaplay Sports 1 HD"},
    {"number": "552", "name": "Viaplay Sports 2 HD"},
    {"number": "553", "name": "Viaplay Xtra"},
    {"number": "601", "name": "BBC News HD"},
    {"number": "602", "name": "Sky News/HD"},
    {"number": "604", "name": "GB News"},
    {"number": "605", "name": "BBC Parliament"},
    {"number": "606", "name": "TalkTV"},
    {"number": "609", "name": "Bloomberg HD"},
    {"number": "613", "name": "CNBC"},
    {"number": "614", "name": "NBC News NOW HD"},
    {"number": "620", "name": "Euronews"},
    {"number": "621", "name": "NDTV 24x7"},
    {"number": "622", "name": "Al Jazeera English"},
    {"number": "624", "name": "France 24 English HD"},
    {"number": "625", "name": "NHKworld HD"},
    {"number": "700", "name": "Kids TV On Demand"},
    {"number": "701", "name": "CBBC HD"},
    {"number": "702", "name": "CBeebies HD"},
    {"number": "703", "name": "Baby TV"},
    {"number": "704", "name": "Cartoon Network HD"},
    {"number": "702", "name": "CBeebies HD"},
    {"number": "703", "name": "Baby TV"},
    {"number": "704", "name": "Cartoon Network HD"},
    {"number": "705", "name": "Cartoon Network +1"},
    {"number": "706", "name": "Cartoonito"},
    {"number": "707", "name": "Sky Kids HD"},
    {"number": "712", "name": "Nickelodeon HD"},
    {"number": "713", "name": "Nick +1"},
    {"number": "715", "name": "Nick Jr."},
    {"number": "716", "name": "Nick Jr. Too"},
    {"number": "717", "name": "Nicktoons"},
    {"number": "730", "name": "Boomerang"},
    {"number": "731", "name": "Boomerang +1"},
    {"number": "736", "name": "Pop"},
    {"number": "737", "name": "Tiny Pop"},
    {"number": "740", "name": "QVC HD"},
    {"number": "741", "name": "QVC Beauty"},
    {"number": "742", "name": "QVC Style HD"},
    {"number": "743", "name": "QVC Extra"},
    {"number": "748", "name": "Create and Craft"},
    {"number": "755", "name": "Gems TV"},
    {"number": "757", "name": "TJC HD"},
    {"number": "801", "name": "Utsav Gold HD"},
    {"number": "802", "name": "Utsav Bharat"},
    {"number": "803", "name": "Utsav Plus HD"},
    {"number": "805", "name": "SONY TV HD"},
    {"number": "806", "name": "SONY MAX HD"},
    {"number": "807", "name": "SONY SAB"},
    {"number": "808", "name": "SONY MAX 2"},
    {"number": "809", "name": "Zee TV HD"},
    {"number": "810", "name": "Zee Cinema HD"},
    {"number": "815", "name": "B4U Movies"},
    {"number": "816", "name": "B4U Music"},
    {"number": "825", "name": "Colors Gujarati"},
    {"number": "826", "name": "Colors TV HD"},
    {"number": "827", "name": "Colors Rishtey"},
    {"number": "828", "name": "Colors Cineplex"},
    {"number": "829", "name": "NDTV Good Times"},
    {"number": "831", "name": "Al Jazeera Arabic"},
    {"number": "838", "name": "Islam Channel"},
    {"number": "839", "name": "Islam Channel Urdu"},
    {"number": "159", "name": "Regional Channels"},
    {"number": "861", "name": "BBC One London HD"},
    {"number": "862", "name": "BBC One Scotland HD"},
    {"number": "863", "name": "BBC One NI HD"},
    {"number": "864", "name": "BBC One Wales HD"},
    {"number": "865", "name": "BBC Two England HD"},
    {"number": "870", "name": "ITV1"}
];
export default channels;