// generated from https://www.virginmedia.com/content/dam/virginmedia/dotcom/documents/Redwood/ChannelGuide_June2019.pdf
// linked from https://www.virginmedia.com/virgin-tv-edit/tips-and-tricks/virgin-tv-channel-guide
const channels = [
    {"number": "100", "name": "Virgin Media Previews HD"},
    {"number": "101", "name": "BBC One HD"},
    {"number": "102", "name": "BBC Two HD"},
    {"number": "103", "name": "ITV1 HD"},
    {"number": "104", "name": "Channel 4 HD"},
    {"number": "105", "name": "Channel 5 HD"},
    {"number": "106", "name": "E4 HD"},
    {"number": "107", "name": "BBC Three HD"},
    {"number": "108", "name": "BBC Four HD"},
    {"number": "109", "name": "Sky Showcase HD"},
    {"number": "110", "name": "Sky Witness HD"},
    {"number": "111", "name": "Sky Max HD"},
    {"number": "112", "name": "Sky Comedy HD"},
    {"number": "114", "name": "ITV1 +1"},
    {"number": "115", "name": "ITV2 HD"},
    {"number": "116", "name": "ITV2 +1"},
    {"number": "117", "name": "ITV3 HD"},
    {"number": "118", "name": "ITV4 HD"},
    {"number": "119", "name": "ITVBe HD"},
    {"number": "120", "name": "ITVBe +1/BBC Alba*"},
    {"number": "121", "name": "Sky Crime HD"},
    {"number": "122", "name": "Sky Sci-Fi HD"},
    {"number": "123", "name": "Sky Arts HD"},
    {"number": "124", "name": "GOLD HD"},
    {"number": "125", "name": "W HD"},
    {"number": "126", "name": "alibi HD"},
    {"number": "127", "name": "Dave HD"},
    {"number": "128", "name": "Really"},
    {"number": "129", "name": "Yesterday HD"},
    {"number": "130", "name": "Drama HD"},
    {"number": "131", "name": "Dave ja vu"},
    {"number": "132", "name": "Comedy Central HD"},
    {"number": "133", "name": "Comedy Central +1"},
    {"number": "134", "name": "MTV HD"},
    {"number": "135", "name": "Pick"},
    {"number": "139", "name": "Challenge"},
    {"number": "140", "name": "Sky Arts"},
    {"number": "142", "name": "Channel 4 +1"},
    {"number": "143", "name": "4Seven HD"},
    {"number": "146", "name": "E4 +1"},
    {"number": "147", "name": "More4 HD"},
    {"number": "148", "name": "CBS Reality"},
    {"number": "149", "name": "Legend"},
    {"number": "150", "name": "5ACTION HD"},
    {"number": "151", "name": "5STAR"},
    {"number": "152", "name": "5Select"},
    {"number": "153", "name": "5 USA"},
    {"number": "154", "name": "Comedy Central Extra"},
    {"number": "155", "name": "Channel 5 +1"},
    {"number": "156", "name": "Sky Replay"},
    {"number": "157", "name": "BBC Three HD*"},
    {"number": "159", "name": "Regional Channels"},
    {"number": "160", "name": "E! HD"},
    {"number": "161", "name": "BBC Alba*"},
    {"number": "162", "name": "BBC Scotland HD/ITVBe +1*"},
    {"number": "163", "name": "Sky Witness +1"},
    {"number": "164", "name": "Sky Crime +1"},
    {"number": "166", "name": "S4C HD*"},
    {"number": "167", "name": "TLC HD"},
    {"number": "168", "name": "Investigation Discovery"},
    {"number": "169", "name": "Quest HD"},
    {"number": "170", "name": "Quest Red"},
    {"number": "171", "name": "DMAX"},
    {"number": "172", "name": "TLC +1"},
    {"number": "173", "name": "Investigation Discovery +1"},
    {"number": "174", "name": "ITV3 +1"},
    {"number": "175", "name": "ITV4 +1"},
    {"number": "181", "name": "Comedy Central"},
    {"number": "185", "name": "5 USA +1"},
    {"number": "186", "name": "5STAR +1"},
    {"number": "189", "name": "GREAT TV"},
    {"number": "190", "name": "W +1"},
    {"number": "191", "name": "alibi +1"},
    {"number": "192", "name": "HorrorXtra"},
    {"number": "194", "name": "GOLD +1"},
    {"number": "196", "name": "More4 +1"},
    {"number": "197", "name": "RealityXtra"},
    {"number": "198", "name": "Crime + Investigation HD"},
    {"number": "199", "name": "BLAZE®"},
    {"number": "204", "name": "Netflix"},
    {"number": "205", "name": "Amazon Prime Video"},
    {"number": "213", "name": "Quest +1"},
    {"number": "214", "name": "DMAX +1"},
    {"number": "217", "name": "Yesterday HD +1"},
    {"number": "218", "name": "CBS Reality +1"},
    {"number": "219", "name": "HorrorXtra +1"},
    {"number": "222", "name": "Crime + Investigation +1"},
    {"number": "226", "name": "Drama HD +1"},
    {"number": "228", "name": "Virgin TV Ultra HD"},
    {"number": "991", "name": "BBC RB HD"},
    {"number": "245", "name": "Eden HD"},
    {"number": "246", "name": "Eden +1"},
    {"number": "250", "name": "Discovery HD"},
    {"number": "251", "name": "Animal Planet HD"},
    {"number": "252", "name": "Discovery Science"},
    {"number": "256", "name": "Discovery Turbo"},
    {"number": "257", "name": "Discovery History"},
    {"number": "258", "name": "Discovery +1"},
    {"number": "259", "name": "Animal Planet +1"},
    {"number": "260", "name": "Discovery Science +1"},
    {"number": "261", "name": "Discovery History +1"},
    {"number": "265", "name": "National Geographic WILD HD"},
    {"number": "266", "name": "National Geographic HD"},
    {"number": "267", "name": "National Geographic +1"},
    {"number": "269", "name": "Together"},
    {"number": "270", "name": "Sky History HD"},
    {"number": "271", "name": "Sky History +1"},
    {"number": "272", "name": "Sky History 2 HD"},
    {"number": "273", "name": "PBS America"},
    {"number": "277", "name": "Sky Documentaries HD"},
    {"number": "278", "name": "Sky Nature HD"},
    {"number": "285", "name": "Food Network"},
    {"number": "286", "name": "HGTV"},
    {"number": "290", "name": "HGTV +1"},
    {"number": "292", "name": "God TV"},
    {"number": "300", "name": "VM Music"},
    {"number": "310", "name": "MTV Music"},
    {"number": "311", "name": "MTV Live HD"},
    {"number": "312", "name": "MTV Hits"},
    {"number": "313", "name": "MTV 90s"},
    {"number": "316", "name": "MTV 80s"},
    {"number": "335", "name": "The Box"},
    {"number": "336", "name": "4Music"},
    {"number": "337", "name": "E4 Extra"},
    {"number": "338", "name": "Kiss"},
    {"number": "340", "name": "Magic"},
    {"number": "342", "name": "Kerrang!"},
    {"number": "344", "name": "Vevo"},
    {"number": "345", "name": "Clubland TV"},
    {"number": "346", "name": "Now 70s"},
    {"number": "347", "name": "Now 80s"},
    {"number": "348", "name": "NOW ROCK"},
    {"number": "400", "name": "Virgin Movies Previews"},
    {"number": "401", "name": "Sky Cinema Premiere HD"},
    {"number": "402", "name": "Sky Cinema Select HD"},
    {"number": "403", "name": "Sky Cinema Hits HD"},
    {"number": "404", "name": "Sky Cinema Greats HD"},
    {"number": "406", "name": "Sky Cinema Family HD"},
    {"number": "407", "name": "Sky Cinema Action HD"},
    {"number": "408", "name": "Sky Cinema Comedy HD"},
    {"number": "409", "name": "Sky Cinema Thriller HD"},
    {"number": "410", "name": "Sky Cinema Drama HD"},
    {"number": "411", "name": "Sky Cinema Sci-Fi & Horror HD"},
    {"number": "412", "name": "Sky Cinema Animation HD"},
    {"number": "415", "name": "TCM Movies HD"},
    {"number": "417", "name": "TCM Movies +1"},
    {"number": "419", "name": "Movies 24"},
    {"number": "420", "name": "Movies 24 +"},
    {"number": "424", "name": "Great! Romance"},
    {"number": "425", "name": "Great! Movies"},
    {"number": "426", "name": "Great! Action"},
    {"number": "428", "name": "Film4 HD"},
    {"number": "430", "name": "Film4 +1"},
    {"number": "445", "name": "Talking Pictures TV"},
    {"number": "501", "name": "Sky Sports Main Event HD"},
    {"number": "502", "name": "Sky Sports Premier League HD"},
    {"number": "503", "name": "Sky Sports Football HD"},
    {"number": "504", "name": "Sky Sports Cricket HD"},
    {"number": "505", "name": "Sky Sports Golf HD"},
    {"number": "506", "name": "Sky Sports F1® HD"},
    {"number": "507", "name": "Sky Sports NFL HD"},
    {"number": "508", "name": "Sky Sports Arena HD"},
    {"number": "509", "name": "Sky Sports News HD"},
    {"number": "510", "name": "Sky Sports Mix HD"},
    {"number": "511", "name": "Sky Sports Main Event"},
    {"number": "512", "name": "Sky Sports Premier League"},
    {"number": "513", "name": "Sky Sports Football"},
    {"number": "514", "name": "Sky Sports Cricket"},
    {"number": "515", "name": "Sky Sports Golf"},
    {"number": "516", "name": "Sky Sports F1®"},
    {"number": "517", "name": "Sky Sports NFL"},
    {"number": "518", "name": "Sky Sports Arena"},
    {"number": "521", "name": "Eurosport 1 HD"},
    {"number": "522", "name": "Eurosport 2 HD"},
    {"number": "526", "name": "MUTV"},
    {"number": "527", "name": "BT Sport 1 HD"},
    {"number": "528", "name": "BT Sport 2 HD"},
    {"number": "529", "name": "BT Sport 3 HD"},
    {"number": "530", "name": "BT Sport 4 HD"},
    {"number": "531", "name": "BT Sport Ultimate"},
    {"number": "532", "name": "Sky Sports Main Event UHD"},
    {"number": "533", "name": "Sky Sports F1® UHD"},
    {"number": "534", "name": "Sky Sports UHD"},
    {"number": "535", "name": "Sky Sports Racing HD"},
    {"number": "536", "name": "Racing TV HD"},
    {"number": "544", "name": "LFC TV HD"},
    {"number": "551", "name": "Viaplay Sports 1 HD"},
    {"number": "552", "name": "Viaplay Sports 2 HD"},
    {"number": "553", "name": "Viaplay Xtra"},
    {"number": "601", "name": "BBC News HD"},
    {"number": "602", "name": "Sky News HD"},
    {"number": "603", "name": "Sky News"},
    {"number": "604", "name": "GB News"},
    {"number": "605", "name": "BBC Parliament"},
    {"number": "606", "name": "TalkTV"},
    {"number": "609", "name": "Bloomberg HD"},
    {"number": "613", "name": "CNBC"},
    {"number": "614", "name": "NBC News NOW HD"},
    {"number": "620", "name": "Euronews"},
    {"number": "621", "name": "NDTV 24x7"},
    {"number": "622", "name": "Al Jazeera English"},
    {"number": "624", "name": "France 24 English HD"},
    {"number": "625", "name": "NHKworld HD"},
    {"number": "701", "name": "CBBC HD"},
    {"number": "702", "name": "CBeebies HD"},
    {"number": "704", "name": "Cartoon Network HD"},
    {"number": "705", "name": "Cartoon Network +1"},
    {"number": "706", "name": "Cartoonito"},
    {"number": "707", "name": "Sky Kids"},
    {"number": "712", "name": "Nickelodeon HD"},
    {"number": "713", "name": "Nick +1"},
    {"number": "715", "name": "Nick Jr."},
    {"number": "716", "name": "Nick Jr. Too"},
    {"number": "717", "name": "Nicktoons"},
    {"number": "730", "name": "Boomerang"},
    {"number": "731", "name": "Boomerang +1"},
    {"number": "734", "name": "CITV"},
    {"number": "736", "name": "Pop"},
    {"number": "737", "name": "Tiny Pop"},
    {"number": "740", "name": "QVC HD"},
    {"number": "741", "name": "QVC Beauty"},
    {"number": "742", "name": "QVC Style HD"},
    {"number": "743", "name": "QVC Extra"},
    {"number": "747", "name": "Ideal World"},
    {"number": "748", "name": "Create and Craft"},
    {"number": "755", "name": "Gems TV"},
    {"number": "901", "name": "BBC Radio 1"},
    {"number": "902", "name": "BBC Radio 2"},
    {"number": "903", "name": "BBC Radio 3"},
    {"number": "904", "name": "BBC Radio 4"},
    {"number": "905", "name": "BBC Radio 5 Live"},
    {"number": "906", "name": "BBC World Service"},
    {"number": "907", "name": "BBC Radio 1 Xtra"},
    {"number": "908", "name": "BBC Radio 5 Live Sports Extra"},
    {"number": "909", "name": "BBC Radio 6 Music"},
    {"number": "910", "name": "BBC Radio 4 Extra"},
    {"number": "911", "name": "BBC Radio 4 LW"},
    {"number": "912", "name": "BBC Asian Network"},
    {"number": "913", "name": "BBC Radio Cymru 2"},
    {"number": "915", "name": "Absolute Radio"},
    {"number": "916", "name": "Smooth Radio"},
    {"number": "917", "name": "RTE Radio"},
    {"number": "918", "name": "Heart FM"},
    {"number": "919", "name": "LBC"},
    {"number": "920", "name": "World Radio Network"},
    {"number": "921", "name": "Heart 80s"},
    {"number": "922", "name": "Classic FM"},
    {"number": "923", "name": "Gold"},
    {"number": "924", "name": "Planet Rock"},
    {"number": "927", "name": "talkSPORT"},
    {"number": "928", "name": "Magic Radio"},
    {"number": "930", "name": "BBC Radio Scotland"},
    {"number": "931", "name": "BBC Radio Wales"},
    {"number": "932", "name": "BBC Radio Ulster"},
    {"number": "933", "name": "BBC Radio Foyle"},
    {"number": "934", "name": "BBC Radio NanGaidheal"},
    {"number": "936", "name": "BBC Radio Cymru"},
    {"number": "937", "name": "BBC London"},
    {"number": "951", "name": "Absolute 80s"},
    {"number": "952", "name": "Absolute Classic Rock"},
    {"number": "958", "name": "Capital"},
    {"number": "959", "name": "Capital XTRA"},
    {"number": "960", "name": "Radio X"},
    {"number": "963", "name": "Kiss FM"},
];
export default channels;