name: create apps
on:
  push:
    tags:
      - '*'
defaults:
  run:
    shell: bash
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true
      - name: Setup node_modules
        run: yarn install --frozen-lockfile
      - name: Build UI
        run: yarn build
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Create Distribution
        id: create_dist
        run: |
          cd build
          tar cfz ../ezmote-${{ steps.get_version.outputs.version-without-v }}.tar.gz *
          cd ..
          echo ::set-output name=binary_path::"ezmote-${{ steps.get_version.outputs.version-without-v }}.tar.gz"
          echo ::set-output name=binary_name::"ezmote-${{ steps.get_version.outputs.version-without-v }}.tar.gz"
          echo ::set-output name=binary_content_type::"application/x-tar"
      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: ${{ steps.create_dist.outputs.binary_name }}
          asset_path: ${{ steps.create_dist.outputs.binary_path }}
          asset_content_type: ${{ steps.create_dist.outputs.binary_content_type }}
